from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class GeneratedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='generated_images')
    prompt = models.TextField()
    negative_prompt = models.TextField(blank=True, null=True)
    image_data = models.TextField()  # Stores base64 encoded image
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"Image generated by {self.user.username} at {self.created_at}"