# Generated by Django 5.1.1 on 2024-11-25 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profile_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
    ]
