# Generated by Django 5.1.1 on 2025-03-09 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=150)),
                ("cloth_type", models.CharField(max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new_with_tag", "New with Tag"),
                            ("like_new", "Like New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("universal", "Universal"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shirts", "Shirts"),
                            ("pants", "Pants"),
                            ("jackets", "Jackets"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cloth_image1", models.ImageField(upload_to="donations/")),
                (
                    "cloth_image2",
                    models.ImageField(blank=True, null=True, upload_to="donations/"),
                ),
                (
                    "cloth_image3",
                    models.ImageField(blank=True, null=True, upload_to="donations/"),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("xl", "XL"),
                            ("xxl", "XXL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "seasonal_clothing",
                    models.CharField(
                        choices=[
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                            ("all_seasons", "All Seasons"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pick_up_address", models.TextField()),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("unknown", "Unknown"),
                            ("expired", "Expired"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pickup_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DonationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_reason",
                    models.CharField(
                        choices=[
                            ("personal_need", "Personal Need"),
                            ("family_need", "Family Need"),
                            ("community_program", "Community Program"),
                            ("homeless_shelter", "Homeless Shelter"),
                            ("disaster_relief", "Disaster Relief"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                ("phone_no", models.CharField(max_length=11)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("full_filled", "Full Filled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="donation.donation",
                    ),
                ),
                (
                    "donee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("donee", "donation")},
            },
        ),
    ]
