# Generated by Django 5.1.1 on 2025-03-29 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0003_donation_donee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="donee",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="full_name",
        ),
    ]
