# Generated by Django 5.1.1 on 2025-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0004_remove_donation_donee_remove_donation_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
