# Generated by Django 5.1.7 on 2025-04-03 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donation", "0005_donation_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="pickup_deadline",
        ),
    ]
