# Generated by Django 4.2.4 on 2025-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_remove_donation_pickup_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='cloth_image1',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cloth_image2',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cloth_image3',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated_user',
        ),
        migrations.AddField(
            model_name='donation',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('requested', 'Requested'), ('approved', 'Approved'), ('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('full_filled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
