# Generated by Django 4.2.4 on 2025-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_remove_donation_cloth_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='seasonal_clothing',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_seasons', 'All Seasons')], default='all_seasons', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('expired', 'Expired')], default='live', max_length=20),
        ),
    ]
