# Generated by Django 4.2.4 on 2025-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_donation_seasonal_clothing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
