// ===============================================
// DONATION MODULE CONSTANTS
// ===============================================

// Donation submission constants - Used when a user submits a new donation
export const DONATION_SUBMIT_REQUEST = "DONATION_SUBMIT_REQUEST"
export const DONATION_SUBMIT_SUCCESS = "DONATION_SUBMIT_SUCCESS"
export const DONATION_SUBMIT_FAIL = "DONATION_SUBMIT_FAIL"
export const DONATION_SUBMIT_RESET = "DONATION_SUBMIT_RESET"

// Donation list constants - Used when fetching a list of donations
export const DONATION_LIST_REQUEST = "DONATION_LIST_REQUEST"
export const DONATION_LIST_SUCCESS = "DONATION_LIST_SUCCESS"
export const DONATION_LIST_FAIL = "DONATION_LIST_FAIL"

// Donation details constants - Used when fetching details of a specific donation
export const DONATION_DETAILS_REQUEST = "DONATION_DETAILS_REQUEST"
export const DONATION_DETAILS_SUCCESS = "DONATION_DETAILS_SUCCESS"
export const DONATION_DETAILS_FAIL = "DONATION_DETAILS_FAIL"

// Donation update constants - Used when updating an existing donation
export const DONATION_UPDATE_REQUEST = "DONATION_UPDATE_REQUEST"
export const DONATION_UPDATE_SUCCESS = "DONATION_UPDATE_SUCCESS"
export const DONATION_UPDATE_FAIL = "DONATION_UPDATE_FAIL"
export const DONATION_UPDATE_RESET = "DONATION_UPDATE_RESET"

// Donation delete constants - Used when deleting a donation
export const DONATION_DELETE_REQUEST = "DONATION_DELETE_REQUEST"
export const DONATION_DELETE_SUCCESS = "DONATION_DELETE_SUCCESS"
export const DONATION_DELETE_FAIL = "DONATION_DELETE_FAIL"
export const DONATION_DELETE_RESET = "DONATION_DELETE_RESET"

// Donation request submission constants - Used when a user submits a request for a donation
export const DONATION_REQUEST_SUBMIT_REQUEST = "DONATION_REQUEST_SUBMIT_REQUEST"
export const DONATION_REQUEST_SUBMIT_SUCCESS = "DONATION_REQUEST_SUBMIT_SUCCESS"
export const DONATION_REQUEST_SUBMIT_FAIL = "DONATION_REQUEST_SUBMIT_FAIL"
export const DONATION_REQUEST_SUBMIT_RESET = "DONATION_REQUEST_SUBMIT_RESET"

// Donation request list constants - Used when fetching a list of donation requests
export const DONATION_REQUEST_LIST_REQUEST = "DONATION_REQUEST_LIST_REQUEST"
export const DONATION_REQUEST_LIST_SUCCESS = "DONATION_REQUEST_LIST_SUCCESS"
export const DONATION_REQUEST_LIST_FAIL = "DONATION_REQUEST_LIST_FAIL"

// Donation request update constants - Used when updating a donation request
export const DONATION_REQUEST_UPDATE_REQUEST = "DONATION_REQUEST_UPDATE_REQUEST"
export const DONATION_REQUEST_UPDATE_SUCCESS = "DONATION_REQUEST_UPDATE_SUCCESS"
export const DONATION_REQUEST_UPDATE_FAIL = "DONATION_REQUEST_UPDATE_FAIL"
export const DONATION_REQUEST_UPDATE_RESET = "DONATION_REQUEST_UPDATE_RESET"

// Donation request delete constants - Used when deleting a donation request
export const DONATION_REQUEST_DELETE_REQUEST = "DONATION_REQUEST_DELETE_REQUEST"
export const DONATION_REQUEST_DELETE_SUCCESS = "DONATION_REQUEST_DELETE_SUCCESS"
export const DONATION_REQUEST_DELETE_FAIL = "DONATION_REQUEST_DELETE_FAIL"
export const DONATION_REQUEST_DELETE_RESET = "DONATION_REQUEST_DELETE_RESET"

// File upload constants - Used when uploading files (images, documents)
export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST"
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
export const FILE_UPLOAD_FAIL = "FILE_UPLOAD_FAIL"
export const FILE_UPLOAD_RESET = "FILE_UPLOAD_RESET"

// Donor rating constants - Used for rating donors
export const DONOR_RATING_SUBMIT_REQUEST = "DONOR_RATING_SUBMIT_REQUEST"
export const DONOR_RATING_SUBMIT_SUCCESS = "DONOR_RATING_SUBMIT_SUCCESS"
export const DONOR_RATING_SUBMIT_FAIL = "DONOR_RATING_SUBMIT_FAIL"
export const DONOR_RATING_SUBMIT_RESET = "DONOR_RATING_SUBMIT_RESET"

export const DONOR_RATINGS_LIST_REQUEST = "DONOR_RATINGS_LIST_REQUEST"
export const DONOR_RATINGS_LIST_SUCCESS = "DONOR_RATINGS_LIST_SUCCESS"
export const DONOR_RATINGS_LIST_FAIL = "DONOR_RATINGS_LIST_FAIL"

// Donee rating constants - Used for rating donees
export const DONEE_RATING_SUBMIT_REQUEST = "DONEE_RATING_SUBMIT_REQUEST"
export const DONEE_RATING_SUBMIT_SUCCESS = "DONEE_RATING_SUBMIT_SUCCESS"
export const DONEE_RATING_SUBMIT_FAIL = "DONEE_RATING_SUBMIT_FAIL"
export const DONEE_RATING_SUBMIT_RESET = "DONEE_RATING_SUBMIT_RESET"

export const DONEE_RATINGS_LIST_REQUEST = "DONEE_RATINGS_LIST_REQUEST"
export const DONEE_RATINGS_LIST_SUCCESS = "DONEE_RATINGS_LIST_SUCCESS"
export const DONEE_RATINGS_LIST_FAIL = "DONEE_RATINGS_LIST_FAIL"

// Status change constants for donations
export const DONATION_APPROVE_REQUEST = "DONATION_APPROVE_REQUEST"
export const DONATION_APPROVE_SUCCESS = "DONATION_APPROVE_SUCCESS"
export const DONATION_APPROVE_FAIL = "DONATION_APPROVE_FAIL"
export const DONATION_APPROVE_RESET = "DONATION_APPROVE_RESET"

export const DONATION_REJECT_REQUEST = "DONATION_REJECT_REQUEST"
export const DONATION_REJECT_SUCCESS = "DONATION_REJECT_SUCCESS"
export const DONATION_REJECT_FAIL = "DONATION_REJECT_FAIL"
export const DONATION_REJECT_RESET = "DONATION_REJECT_RESET"

export const DONATION_EXPIRE_REQUEST = "DONATION_EXPIRE_REQUEST"
export const DONATION_EXPIRE_SUCCESS = "DONATION_EXPIRE_SUCCESS"
export const DONATION_EXPIRE_FAIL = "DONATION_EXPIRE_FAIL"
export const DONATION_EXPIRE_RESET = "DONATION_EXPIRE_RESET"

// Status change constants for requests
export const REQUEST_EXPIRE_REQUEST = "REQUEST_EXPIRE_REQUEST"
export const REQUEST_EXPIRE_SUCCESS = "REQUEST_EXPIRE_SUCCESS"
export const REQUEST_EXPIRE_FAIL = "REQUEST_EXPIRE_FAIL"
export const REQUEST_EXPIRE_RESET = "REQUEST_EXPIRE_RESET"

