export const IMAGE_GENERATION_REQUEST = "IMAGE_GENERATION_REQUEST"
export const IMAGE_GENERATION_SUCCESS = "IMAGE_GENERATION_SUCCESS"
export const IMAGE_GENERATION_FAILURE = "IMAGE_GENERATION_FAILURE"
export const IMAGE_GENERATION_RESET = "IMAGE_GENERATION_RESET"

export const USER_IMAGES_REQUEST = "USER_IMAGES_REQUEST"
export const USER_IMAGES_SUCCESS = "USER_IMAGES_SUCCESS"
export const USER_IMAGES_FAILURE = "USER_IMAGES_FAILURE"     