export const UPLOAD_CLOTH_IMAGE_REQUEST = "UPLOAD_CLOTH_IMAGE_REQUEST"
export const UPLOAD_CLOTH_IMAGE_SUCCESS = "UPLOAD_CLOTH_IMAGE_SUCCESS"
export const UPLOAD_CLOTH_IMAGE_FAILURE = "UPLOAD_CLOTH_IMAGE_FAILURE"

export const UPLOAD_HUMAN_IMAGE_REQUEST = "UPLOAD_HUMAN_IMAGE_REQUEST"
export const UPLOAD_HUMAN_IMAGE_SUCCESS = "UPLOAD_HUMAN_IMAGE_SUCCESS"
export const UPLOAD_HUMAN_IMAGE_FAILURE = "UPLOAD_HUMAN_IMAGE_FAILURE"

export const PERFORM_VIRTUAL_TRY_ON_REQUEST = "PERFORM_VIRTUAL_TRY_ON_REQUEST"
export const PERFORM_VIRTUAL_TRY_ON_SUCCESS = "PERFORM_VIRTUAL_TRY_ON_SUCCESS"
export const PERFORM_VIRTUAL_TRY_ON_FAILURE = "PERFORM_VIRTUAL_TRY_ON_FAILURE"

export const FETCH_VTON_HISTORY_REQUEST = "FETCH_VTON_HISTORY_REQUEST"
export const FETCH_VTON_HISTORY_SUCCESS = "FETCH_VTON_HISTORY_SUCCESS"
export const FETCH_VTON_HISTORY_FAILURE = "FETCH_VTON_HISTORY_FAILURE"